In [33]:
import os
os.getcwd()
os.chdir('d:\\bot_telegram_customer_support\\sheets')

import utils
import pandas as pd

In [34]:
sh = utils.getGoogleSpreadsheet(
        'credentials.json',
        utils.ACCOUNT_STATE_SHEET_KEY
)
sheet = utils.getOrCreateGoogleWorksheet(sh, 'Ingreso Pago Movil')
df = pd.DataFrame(sheet.get_all_records())
#df['USD'][2]
df

,Fecha,Referencia,Descripción,Monto,USD,Estado
0,15/06/2021,11666180480,Banesco Pago Movil,"32.118.795,93",,No Verificado
1,16/06/2021,63959863959,Banesco Pago Movil,"2.400.000,00",,No Verificado
2,16/06/2021,32835272414,Banesco Pago Movil,"3.823.360,00",,No Verificado
3,16/06/2021,61010011128,Banesco Pago Movil,"3.994.000,00",,No Verificado
4,16/06/2021,62911005227,Banesco Pago Movil,"12.209.000,00",,No Verificado
5,16/06/2021,11676720865,Banesco Pago Movil,"1.300.000,00",,No Verificado
6,16/06/2021,11677113975,Banesco Pago Movil,"25.280.000,00",,No Verificado
7,21/06/2021,21633003830,Banesco Pago Movil,"8.040.000,00",,No Verificado
8,21/06/2021,15133365687,Banesco Pago Movil,"17.560.000,00",,No Verificado
9,23/06/2021,11741734025,Banesco Pago Movil,"7.600.000,00",,No Verificado
10,25/06/2021,51518011174,Banesco Pago Movil,"7.215.157,00",,No Verificado
11,25/06/2021,2285402285,Banesco Pago Movil,"3.200.000,00",,No Verificado
12,29/06/2021,62779562779,Banesco Pago Movil,"2.880.000,00",,No Verificado
13,29/06/2021,61943661943,Banesco Pago Movil,"6.041.280,00",,Verificado
14,30/06/2021,93931005328,Banesco Pago Movil,"20.124.000,00",,Verificado
15,01/07/2021,86306786306,Banesco Pago Movil,"6.400.000,00",,Verificado

In [42]:
df = df[['Fecha', 'Referencia', 'Monto', 'Estado']]
df = df.loc[df['Estado'] == 'Verificado']
df = df[['Fecha', 'Referencia', 'Monto', ]]
df

         Fecha   Referencia          Monto
13  29/06/2021  61943661943   6.041.280,00
14  30/06/2021  93931005328  20.124.000,00
15  01/07/2021  86306786306   6.400.000,00